version: "3.5"
services:
  post-storage-mongodb1:
    image: mongo
    container_name: post_storage_mongodb1
    networks:
      - serverless1
    ports:
      - 17017:27017
    restart: always

  social-graph-mongodb1:
    image: mongo
    container_name: social_graph_mongodb1
    networks:
      - serverless1
    ports:
      - 17018:27017
    restart: always

  user-timeline-mongodb1:
    image: mongo
    container_name: user_timeline_mongodb1
    networks:
      - serverless1
    ports:
      - 17019:27017
    restart: always

  home-timeline-mongodb1:
    image: mongo
    container_name: home_timeline_mongodb1
    networks:
      - serverless1
    ports:
      - 17020:27017
    restart: always

  couchserver1:
    image: couchdb
    ports:
      - "5985:5984"
    environment:
      - COUCHDB_USER=whisk_admin
      - COUCHDB_PASSWORD=some_passw0rd
    volumes:
        - ./dbdata:/opt/couchdb1/data
    restart: always

networks:
  serverless1:
    driver: bridge 
